version: 0.0
os: linux
files:
  - source: /
    destination: /home/hr-app/
hooks:
  AfterInstall:
    - location: scripts/install_deps
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
