#!/bin/bash

# Install node.js
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
. ~/.nvm/nvm.sh
nvm install 16
npm install pm2@latest -g

node -e "console.log('Running Node.js ' + process.version)"

cd /home/hr-app/
npm install
npm run docs