name: Node.js CI

on:
  push:
    branches: [ dev ]

jobs:
  compress:
    runs-on: ubuntu-latest

    container:
      image: node:latest

    steps:
      - uses: actions/checkout@v2

      - name: Compress
        run: |
          archive=$(npm pack)
          mv $archive tc-backend.tgz

      - name: Install dependencies
        run: npm ci

      - name: Generate Documentation
        run: npm run docs

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: tc-backend
          path: tc-backend.tgz

  deploy:
    needs: compress
    runs-on: ubuntu-latest

    container:
      image: python:latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install AWS CLI
        run: pip install awscli

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: tc-backend
          path: .

      - name: Deploy to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: aws s3 cp ./tc-backend.tgz s3://${{ secrets.S3_BACKEND_BUCKET }}/tc-backend.tgz
