name: CI/CD Pipeline

on:
  push:
    branches: [ dev ]

jobs:
  prepare:
    runs-on: ubuntu-latest

    container:
      image: node:latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

  build:
    needs: prepare
    runs-on: ubuntu-latest
    container: node:latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Packages
        run: npm update

      - name: Build
        run: npm run build

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    container: python:latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Install AWS CLI
        run: pip install awscli

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          S3_FRONTEND_BUCKET: ${{ secrets.S3_FRONTEND_BUCKET }}
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
        run: |
          aws s3 rm s3://$S3_FRONTEND_BUCKET --recursive
          aws s3 cp ./dist/ s3://$S3_FRONTEND_BUCKET --recursive --include "*"
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'